---
title: "Exam 2"
author: "Divya Koothan"
date: "6/26/2020"
output: word_document
toc: TRUE
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
1. #clear global environment 
rm(list = ls(all = TRUE))
```


```{r}
2. #loading rio library to import ineqaulity excel sheet
library(rio)
inequality_data <- import("inequality.xlsx")
```


3. The dataset is a cross-section data set, because it shows a snapshot in time for the year 2015. 
```{r}
#viewing data set to determine cross sectional or not 
summary(inequality_data)
```


```{r}
4. #subset Gini index for Sweden and Denmark
subset(inequality_data, select = c("country", "inequality_gini"), country == "Sweden"|country == "Denmark")
```


```{r}
5. #subset gini index for Brazil
subset(inequality_data, select = c("country", "inequality_gini"), country == "Brazil")
```


6. It is better to have a low inequality_gini score.


```{r}
7. #peak at dataframe
head(inequality_data)
```


```{r}
8.#create function
remove.accents <- function(s){
  #1 character substitutions
  old1 <- "ú"
  new1 <- "u"
  s1  <-chartr(old1,new1, s)
  
}

#apply function
inequality_data$country <- remove.accents(inequality_data$country)
#checking if function worked
head(inequality_data)
```


```{r}
9. #sorting inequality_gini by lowest score
inequality_data <- inequality_data[order(inequality_data$inequality_gini),]
#the top 5
head(inequality_data, 5)
```


10. The mean inequality_gini is 36.81375
```{r}
#finding the average inequality_gini
mean(inequality_data$inequality_gini, na.rm = TRUE)
```


```{r}
11. #creating a new variable 
library(tidyverse)
#low inequality
inequality_data  <-
  inequality_data %>%
  mutate(low_inequality = 
           ifelse( inequality_gini < 36.81375, 
                  1, 0))
#high inequality 
inequality_data  <-
  inequality_data %>%
  mutate(high_inequality = 
           ifelse( inequality_gini >= 36.81375, 
                   1, 0))
```


```{r}
12. #running a crosstab
library(doBy)
summaryBy(high_inequality ~ low_inequality, inequality_data, FUN = c(mean, length))
```


```{r}
13. #created a vector with the names
reduce_inequality_africa <- c("World Bank", "African Development Bank", "Bill and Melida Gates")
#created for loop to print
for (i in reduce_inequality_africa){
  print(i)
}
```


14. The percentage of females enrolled in primary education seems like a good indicator for inequality. If there is a low enrollment, there is likely to be more inequality 


```{r}
15.#load the WDI
library(WDI)
#importing data
education_pupil <- WDI(country = "all",
                  indicator =c ("SE.PRM.ENRL.FE.ZS"),
                  start = 2015, end = 2015, extra = FALSE, cache = NULL)
```


```{r}
16. #loading data.table
library(data.table)
#changing variable name
setnames(female_edu, "SE.PRM.ENRL.FE.ZS", "female_enrollment")
```


```{r}
17.#mergeing the data together 
merged_df <- left_join(inequality_data, female_edu,
                        by = c("iso2c", "year", "country"))
```


```{r}
18.#removing NA based on ig
merged_df <- na.omit(merged_df, 
                     select <- "inequality_gini")
#check if it worked
any(is.na(merged_df))
```


```{r}
19.#using filter and piping to select data
#that is greater than 30
#loading dplyr
library(dplyr)
data_greater_30 <-
  merged_df %>%
  dplyr::filter(inequality_gini > 30)
```


```{r}
20.#find count of cournty with "ai"
length(grep("ai", data_greater_30$country))
```


```{r}
21. #taking the sum of inequality-gini
sapply(data_greater_30$inequality_gini, sum)
#this would be the acutal sum 
sum(data_greater_30$inequality_gini)
```


```{r}
22. #labelling the variables 
#load labelled
library(labelled)
var_label(merged_df) <- list(`iso2c` = "iso2c",
                             `country` = "country",
                             `inequality_gini` = "inequality Gini Index",
                             `year` = "year",
                             `low_inequality` = "below average inequality gini",
                             `high_inequality` = "abover average inequality gini",
                             `female_enrollment` = "% of femaled enrolled in primary education")
```


```{r}
23. #save the data fram as a stata dataset
library(rio)
export(merged_df, "final_data.dta")
```


```{r}
24. #GitHub repo link 
```

